### ISSUE TITLE
[1.20.1] Stacks quantity is become 32 instead of 64 when Dimension Card is inserted.

### ISSUE THREAD

**Issue by MPThLee** [Hexeption/AEInfinityBooster#14]
On All The Mods 9, 0.0.49. AE is 15.0.9-beta, AEIB is 1.20.1-1.0.0+20

When shift-click the stack of item, it became 32 per each click. See the video. See also AllTheMods/ATM-9#217

https://github.com/Hexeption/AEInfinityBooster/assets/26970092/e9afc590-b9bd-4a0a-abeb-ee936be569dd

**Comment by unejamzezak** [comment]
I have this same issue but when I shift+click it only pulls out 16 per item.

**Comment by 7Kav** [comment]
the issue is weird but I found it to be about which card you put in

Infinity range = 16 per click
Dimension = 32 per click

**Comment by DrPinguin98** [comment]
Same problem...
Wonder why this bug has not been fixed after almost 1 month?

**Comment by AzuluTheShnepsky** [comment]
I´m not an expert and i could be wrong but looking through the mod it looks like that its intentional by the author
`  if (wirelessBlockEntity.getInternalInventory().getStackInSlot(0).is(ModItems.DIMENSION_CARD.get())) {
                currentDistanceFromGrid = 32;
                cir.setReturnValue(Double.MAX_VALUE / 2);
            }

            if (!this.getPlayer().level().dimension().location().toString().equals(wirelessAccessPoint.getLocation().getLevel().dimension().location().toString())) {
                return;
            }

            if (wirelessBlockEntity.getInternalInventory().getStackInSlot(0).is(ModItems.INFINITY_CARD.get())) {
                currentDistanceFromGrid = 16;
                cir.setReturnValue(Double.MAX_VALUE / 2);
            }
        });
    }

    // Make sure we don't use more power than we should
    @Redirect(method = "extractAEPower", at = @At(value = "INVOKE", target = "Ljava/lang/Math;min(DD)D"))
    private double testPowerMultiplier(double a, double b) {
        for (var wap : this.targetGrid.getMachines(WirelessAccessPointBlockEntity.class)) {
            if (wap.getInternalInventory().getStackInSlot(0).is(ModItems.INFINITY_CARD.get())) {
                return 16;
            }
            if (wap.getInternalInventory().getStackInSlot(0).is(ModItems.DIMENSION_CARD.get())) {
                return 32;`

it is annoying and it would be nice to have a config for it

**Comment by MPThLee** [comment]
The 16 and 32 things are for power consumption and override distance to trick the wireless grid as it is working as intended. 
But seems like something went wrong and it broken.

**Comment by Ambossmann** [comment]
This is caused by the following code limiting the energy consumption on every action (like inserting into or extracting from the ME system) instead of just limiting the passive power consumption when the wireless terminal is opened. This causes the ME to think that there is only enough energy stored in the terminal to insert/extract 16/32 items.
```java
// Make sure we don't use more power than we should
@Redirect(method = "extractAEPower", at = @At(value = "INVOKE", target = "Ljava/lang/Math;min(DD)D"))
private double testPowerMultiplier(double a, double b) {
    for (var wap : this.targetGrid.getMachines(WirelessAccessPointBlockEntity.class)) {
        if (wap.getInternalInventory().getStackInSlot(0).is(ModItems.INFINITY_CARD.get())) {
            return 16;
        }
        if (wap.getInternalInventory().getStackInSlot(0).is(ModItems.DIMENSION_CARD.get())) {
            return 32;
        }
    }
    return Math.min(a, b);
}
```

**Comment by djcprone** [comment]
> The 16 and 32 things are for power consumption and override distance to trick the wireless grid as it is working as intended. But seems like something went wrong and it broken.

Could we maybe get a config to up it or could we change an ae2 power draw config to trick it into doing full stacks? between this and the ae2 wireless crafting terminal putting anything over 32 into the offhand slot when you try to deposit, it is nerve racking. Hard to play without the wireless crafting terminal or your mod though. I love them both!

**Comment by ChosenArchitect** [comment]
This is a vanilla thing but this might help:
The "DragonFight" data lives in level.dat; if you delete it from there using an NBT editor while also deleting DIM1 then it should respawn fine.

DragonFight tracks whether there is currently a live dragon, whether a dragon has been killed in the past, which gateways are yet to generate, and where the exit portal is.

**Comment by krispyking24** [comment]
the bug is back its happening for me on forge 1.20.1 mod version https://modrinth.com/mod/aeinfinitybooster/version/1.20.1-1.0.0+20 ae2 version 15.4.8

**Comment by krispyking24** [comment]
nvm modrinth isnt up to date on which versions are released
